apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sonar
  name: sonar
spec:
  containers:
  - image: sonarqube
    name: sonar
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
